### PR TITLE
Confirm Removal of Component, Helper or File

### PR DESCRIPTION
**Pull request by nummi**
I got burned by accidental clicks a few times, thoughts?

screen shot 2017-10-31 at 2 14 40 pm

screen shot 2017-10-31 at 2 14 52 pm

### CODE REVIEW

**Comment by locks** [comment]
It looks a bit out of place @nummi, how would you feel about using the browser's confirm dialog?

**Comment by nummi** [comment]
> It looks a bit out of place @nummi, how would you feel about using the browser's confirm dialog?

@locks, I started with that but the inline confirm _feels_ better. Let me take one more stab at it.

**Comment by nummi** [comment]
Links instead of buttons?

screen shot 2017-11-01 at 2 17 13 pm

**Comment by nummi** [comment]
@locks, change committed. 🎉

**Comment by locks** [comment]
Looking great, thanks!

**Pull request merged**
