### PR TITLE
Header

### PR DESCRIPTION
**Pull request by nummi**
Issue: https://github.com/glimmerjs/glimmer-playground/issues/9

<details>
 <summary>Some options</summary>

screen shot 2017-11-12 at 9 46 46 pm

screen shot 2017-11-12 at 9 46 48 pm

screen shot 2017-11-12 at 9 46 49 pm
</details>

### CODE REVIEW

**Comment by locks** [comment]
cc @tomdale

**Comment by rwjblue** [comment]
I like it, thanks for working on it!

**Comment by locks** [comment]
Quick comments:

1. Is the Glimmer logo clickable?
2. I prefer the middle one, with the add actions as buttons.

**Comment by nummi** [comment]
1. Yes, the Glimmer logo is a link to glimmerjs.com
1. I liked the add icons at first but now I am also in the button camp

**Comment by nummi** [comment]
Here's the latest:

screen shot 2017-11-14 at 9 08 09 pm

**Comment by nummi** [comment]
@tomdale How did I know you'd come in here with your true-sounding platitudes?

A couple options:

screen shot 2017-11-15 at 9 57 33 am
screen shot 2017-11-15 at 10 00 55 am
#EmbraceTheNotch

**Comment by tomdale** [comment]
@nummi Option 2 looks right to me. Amazing work! Thank you for all the time and care you put into this.

**Pull request merged**
